export { default as One } from "./1-intro";
export { default as Quote } from "./quote";
//export { default as Benefits } from "./benefits";
export { default as Two } from "./2-what-is-func";
export { default as Five } from "./5-immutable";
export { default as Four } from "./4-pure";
export { default as Three } from "./3-first-class-func";
export { default } from "./comparison";
export { default as oopquick } from "./oop-quick-sort";
export { default as fquick } from "./functional-quick-sort";
export { default as Questions } from "./999-questions";
